/* eslint-disable no-unused-vars */
export enum CvUploadStatus {
  CV_UPLOAD_SUCCESSFUL = "CV_UPLOAD_SUCCESSFUL",
  CV_UPLOADED_TO_BAD_BUCKET = "CV_UPLOADED_TO_BAD_BUCKET",
  CV_UPLOAD_FAILED_COMPLETELY = "CV_UPLOAD_FAILED_COMPLETELY",
}
